_getGroupesData:
  enabled: true
  lifetime: 86400
_getParlData:
  enabled: true
  lifetime: 86400
_getVacances:
  enabled: true
  lifetime: 604800
_groupes:
  enabled: true
  lifetime: 192800
_newGroupes:
  enabled: true
  lifetime: 192800

